FROM python:3.13.7-slim AS builder

WORKDIR /app

COPY docker_requirements_streamlit.txt .

RUN pip install --no-cache-dir --prefix=/install -r docker_requirements_streamlit.txt


FROM python:3.13.7-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONPATH=/app

RUN useradd --create-home --shell /bin/bush appuser

COPY --from=builder /install /usr/local

COPY --chown=appuser:appuser . .

USER appuser

EXPOSE 8501

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"

CMD [ "streamlit", "run", "streamlit_app/app.py", "--server.address=0.0.0.0", "--server.port=8501" ]