"""rename hushed_password to hashed_password

Revision ID: 04eee973ee99
Revises: 0fec38390602
Create Date: 2026-09-01 19:27:18.432346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '04eee973ee99'
down_revision: Union[str, Sequence[str], None] = '0fec38390602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=100), nullable=False))
    op.drop_column('users', 'hushed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hushed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
