"""Initial schema

Revision ID: c0f2bb7ff63e
Revises: e21b26f43c18
Create Date: 2026-09-08 19:43:38.175274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f2bb7ff63e'
down_revision: Union[str, Sequence[str], None] = 'e21b26f43c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predictions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'user_id')
    # ### end Alembic commands ###
