"""empty message

Revision ID: e21b26f43c18
Revises: 7e6f7217eec2
Create Date: 2026-09-04 10:39:50.949966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e21b26f43c18'
down_revision: Union[str, Sequence[str], None] = '7e6f7217eec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('refresh_tokens', 'exprires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('exprires_at', mysql.DATETIME(), nullable=False))
    op.drop_column('refresh_tokens', 'expires_at')
    # ### end Alembic commands ###
